/**
 * @file:       ZROSDefine.h
 *
 * copyright:   Copyright (c) 2018 ZhenRong Technology, Inc. All rights reserved.
 */

#ifndef ZROSDEFINE_H
#define ZROSDEFINE_H

#if defined(__linux__) || defined(linux) || defined(__linux)
#ifndef _LINUX
#define _LINUX
#endif
#endif
#ifndef _WIN32
#ifdef _LINUX
/*#define _DAO7*/
/*#define _SYLISOS*/
/*#define _ZRDDS_INCLUDE_HR2_SYLIXOS*/
/*#define _ZRDDS_MPORT_SRIO*/
/*#define _ZRDDS_MPORT_FPGA_SRIO*/
/*#define _ZRDDS_INCLUDE_DPDK_ANS*/
/*#define _ZRDDS_TJ_RIO*/
/*#define _SCSD_RIO*/
/*#define _CETC52*/
#else
/*#define _REWORKS*/
/*#define _REWORKS_X86*/
/*#define _REWORKS_TI6678*/
/*#define _REWORKS_FT6678*/
/*#define _ZRDDS_LWIP*/
/*#define _TI6678_RIO*/
/*#define _FT6678_RIO*/
/*#define _ZRDDS_FT_6678_MPORT_SRIO*/
/*#define _VXWORKS*/
/*#define _VXWORKS_66*/
/*#define _VXWORKS_RTP*/
/*#define _BIG_ENDIAN_MACHINE*/

/*#define _HR2_PLATFORM*/
/*#define _HR2_RIO*/
/*#define _HR2_PCIE*/
/*#define _RIO_STATIC_ADDR_CALC_*/
/*#define _BIG_ENDIAN_MACHINE*/
#ifdef _DAO
#define _VXWORKS
#define _VXWORKS_66
#endif

#endif
#endif

#define _ZRXMLQOSINTERFACE
/*#define _ZRXMLENTITYINTERFACE*/
#define _ZRDDSSECURITY
#define _ZRDDSUSERVALIDATE
#define _ZRSHAREDMEMORY
#define _ZRDDS_INCLUDE_MEMORYPOOL
#define _ZRDDS_INCLUDE_TCP
#define _ZRDDS_INCLUDE_TCP_CC_BATCH
/*#define _ZRDDS_ENABLE_RAW_UDP_TRANSFER*/
/*#define _ZRDDS_ENABLE_RAW_TCP_TRANSFER*/
#define _ZRDDS_INCLUDE_TYPE_OBJECT
#define _ZRDDS_INCLUDE_TYPECODE
#define _ZRDDS_INCLUDE_DYNAMIC_DATA
#define _ZRDDS_INCLUDE_CONTENTFILTER_TOPIC
#define _ZRDDS_INCLUDE_GUARD_CONDITION
#define _ZRDDS_INCLUDE_READ_CONDITION 
#define _ZRDDS_INCLUDE_QUERY_CONDITION
#define _ZRDDS_INCLUDE_WAITSET
#define _ZRDDS_INCLUDE_USER_DATA_QOS
#define _ZRDDS_INCLUDE_TOPIC_DATA_QOS
#define _ZRDDS_INCLUDE_GROUP_DATA_QOS
#define _ZRDDS_INCLUDE_TIME_BASED_FILTER_QOS
#define _ZRDDS_INCLUDE_DEADLINE_QOS
#define _ZRDDS_INCLUDE_LIVELINESS_QOS
#define _ZRDDS_INCLUDE_PARTITION_QOS
#define _ZRDDS_INCLUDE_OWNERSHIP_QOS
#define _ZRDDS_INCLUDE_LIFESPAN_QOS
#define _ZRDDS_INCLUDE_PRESENTATION_QOS
#define _ZRDDS_INCLUDE_DESTINATION_ORDER_QOS
#define _ZRDDS_INCLUDE_TRANSPORT_PRIORITY_QOS
#define _ZRDDS_INCLUDE_LATENCY_BUDGET_QOS
#define _ZRDDS_INCLUDE_MSGSTATISTICSINFO_QOS
#define _ZRDDS_INCLUDE_PARTICIPANT_MSG_DATA
#define _ZRDDS_INCLUDE_TOPIC_BUILTIN_TOPIC_DATA
#define _ZRDDS_INCLUDE_BATCH
#define _ZRDDS_AUTO_SORT_ADDR
#define _ZRDDS_INCLUDE_BUILTIN_TYPES
#define _ZRDDS_INCLUDE_PSINTERFACE
#define _ZRDDS_INCLUDE_DIST_LOG
#define _ZRDDS_INCLUDE_INTERACTIVE_COMMAND
#define _ZRDDS_INCLUDE_AUTO_CREATED_PUB_SUB
#define _ZRDDS_INCLUDE_SIMPLE_INTERFACE
#define _ZRDDS_TOPIC_PREMATCH
#define _ZRDDS_INCLUDE_ONSITE_DESERILIZE
#define _ZRDDS_INCLUDE_QUALITY_EVALUATION
/*#define _ZRDDS_INCLUDE_NO_SERIALIZE_MODE*/
/*#define _ZRDDS_INCLUDE_DW_NO_SERIALIZE_MODE*/
/*#define _ZRDDS_INCLUDE_DR_NO_SERIALIZE_MODE*/
/*#define _ZRDDS_INCLUDE_TIMEUTILITY*/
/*#define _ZRDDS_INCLUDE_MULTIPLE_DDS_INSTANCE*/
/*#define _ZRDDS_GENERATOR_DEBUG_INFO*/
/*#define _ZRDDS_SUPPORT_FOR_RECORD_REPLAY*/
#define _ZRDDS_FLOW_CTRL

#if defined(_ZRDDS_INCLUDE_DW_NO_SERIALIZE_MODE) || defined(_ZRDDS_INCLUDE_DR_NO_SERIALIZE_MODE)
#define _ZRDDS_INCLUDE_NO_SERIALIZE_MODE
#endif

/*#define  _ZRDDS_INCLUDE_601_TYPE*/
/*#define _ZRDDS_INCLUDE_READMEMORY*/

#define _ZRDDS_INCLUDE_BREAKPOINT_RESUME
/*端口限制*/
/*#define _ZRDDS_PORT_LIMIT*/
/*稀疏数据类型*/
/*#define _ZRDDS_INCLUDE_SPARE_TYPE*/

#define _ZRDDS_INCLUDE_SET_GUID

/*数据压缩*/
#if defined(_LINUX) || defined(_WIN32)
/*#define _ZRDDS_INCLUDE_DATA_COMPRESSION*/
#endif 
#define _ZRDDS_INCLUDE_BIND_SENDADDR

#define _ZRDDS_INCLUDE_USE_SUBNET
#define _ZRDDS_INCLUDE_ENABLE_SYSTEM_CONFIGURE
/*#define _ZRDDS_INCLUDE_GATEWAY*/
/*#define _ZRDDS_NET_PORT_STARVATION_PREVENT*/
#define _ZRDDS_INCLUDE_CONCURRENT_WRITE
#define _ZRDDS_INCLUDE_MULMAC_WRITE

/*#define _ZRDDS_JAVA*/

#ifdef _ZRDDS_JAVA
/*ZRDDS_JAVA编译需要打开的宏*/
#define _ZRXMLENTITYINTERFACE
#define _ZRDDSSECURITY
#define _ZRDDS_INCLUDE_TYPE_OBJECT
#define _ZRDDS_INCLUDE_TYPECODE
#define _ZRDDS_INCLUDE_CONTENTFILTER_TOPIC
#define _ZRDDS_INCLUDE_GUARD_CONDITION
#define _ZRDDS_INCLUDE_READ_CONDITION
#define _ZRDDS_INCLUDE_QUERY_CONDITION
#define _ZRDDS_INCLUDE_WAITSET
#define _ZRDDS_INCLUDE_USER_DATA_QOS
#define _ZRDDS_INCLUDE_TOPIC_DATA_QOS
#define _ZRDDS_INCLUDE_GROUP_DATA_QOS
#define _ZRDDS_INCLUDE_TIME_BASED_FILTER_QOS
#define _ZRDDS_INCLUDE_PARTITION_QOS
#define _ZRDDS_INCLUDE_OWNERSHIP_QOS
#define _ZRDDS_INCLUDE_LIFESPAN_QOS
#define _ZRDDS_INCLUDE_PRESENTATION_QOS
#define _ZRDDS_INCLUDE_DESTINATION_ORDER_QOS
#define _ZRDDS_INCLUDE_TRANSPORT_PRIORITY_QOS
#define _ZRDDS_INCLUDE_LATENCY_BUDGET_QOS
#define _ZRDDS_INCLUDE_MSGSTATISTICSINFO_QOS
#define _ZRDDS_INCLUDE_BATCH
#define _ZRDDS_ENABLE_RAW_UDP_TRANSFER
#define _ZRDDS_ENABLE_RAW_TCP_TRANSFER
#define _ZRDDS_INCLUDE_ONSITE_DESERILIZE
#define _ZRDDS_INCLUDE_BIND_SENDADDR
#define _ZRDDS_INCLUDE_MULTIPLE_DDS_INSTANCE
#define _ZRDDS_INCLUDE_GATEWAY
#define _ZRDDS_INCLUDE_ENABLE_SYSTEM_CONFIGURE
#define _ZRDDS_INCLUDE_QUALITY_EVALUATION
#endif

#ifdef _ZRDDS_INCLUDE_SIMPLE_INTERFACE
#define _ZRXMLQOSINTERFACE
#endif

#ifdef _ZRXMLENTITYINTERFACE
#define _ZRXMLQOSINTERFACE
#endif 

#ifdef _ZRXMLQOSINTERFACE
#define _ZRXMLINTERFACE
#endif

#ifdef _ZRDDSSECURITY
#define _ZRDDS_INCLUDE_PARTITION_QOS
#define _ZRDDS_INCLUDE_DYNAMIC_DATA
#endif 

#if defined(_ZRDDSSECURITY) || defined(_ZRDDS_INCLUDE_LIVELINESS_QOS)
#define _ZRDDS_INCLUDE_PARTICIPANT_MSG_DATA
#endif 

#ifdef _ZRDDS_INCLUDE_CONTENTFILTER_TOPIC
#define _ZRDDS_INCLUDE_TYPECODE
/*#define _ZRDDS_INCLUDE_TYPE_OBJECT*/
#endif

#ifdef _ZRXMLENTITYINTERFACE
#define _ZRDDS_INCLUDE_DYNAMIC_DATA
#endif 

#ifdef _ZRDDS_INCLUDE_DYNAMIC_DATA
#define _ZRDDS_INCLUDE_TYPECODE
#define _ZRDDS_INCLUDE_TYPE_OBJECT
#endif

#ifdef _ZRDDS_INCLUDE_QUERY_CONDITION
#define _ZRDDS_INCLUDE_READ_CONDITION
#endif

#if defined(_ZRDDS_ENABLE_RAW_UDP_TRANSFER) || defined(_ZRDDS_ENABLE_RAW_TCP_TRANSFER)
#define _ZRDDS_ENABLE_RAW_TRANSFER
#endif

#ifdef _ZRDDS_ENABLE_RAW_TCP_TRANSFER
#ifndef _ZRDDS_INCLUDE_TCP
#define _ZRDDS_INCLUDE_TCP
#endif
#endif

#ifdef _ZRDDS_MPORT_FPGA_SRIO
#ifndef _ZRDDS_MPORT_SRIO
#define _ZRDDS_MPORT_SRIO
#endif
#endif

#ifdef _ZRDDS_FT_6678_MPORT_SRIO
#define _ZRDDS_MPORT_SRIO
#endif

#if defined(_SCSD_RIO) || defined(_TI6678_RIO) || defined(_ZRDDS_TJ_RIO) || defined(_CSIC724_RIO) || defined(_FT6678_RIO) || defined(_HR2_RIO) || defined(_ZRDDS_MPORT_SRIO) || defined(_ZRDDS_INCLUDE_HR2_SYLIXOS)
#ifndef _ZRDDS_RIO
#define _ZRDDS_RIO
#endif
#endif

#ifdef _FT6678_RIO
#define FT_M6678
#endif

#ifdef _HR2_PCIE
#ifndef _ZRDDS_PCIE
#define _ZRDDS_PCIE
#endif
#endif

/* 编译内置安全插件时取消_ZRDDS_INCLUDE_DIST_LOG宏定义 */
#ifdef _ZRDDSSECDLLEXPORT
#undef _ZRDDS_INCLUDE_DIST_LOG
#endif

/*#define _WIN32ONLY*/

#endif
